---
sftp-host: "HOST_NAME"
sftp-port: 22
sftp-user: "USER"
sftp-pass-path: "PATH_TO_FILE"
sftp-input-folder: "PATH_TO_FOLDER"
sftp-output-folder: "PATH_TO_FOLDER"
sftp-archive-folder: "PATH_TO_FOLDER"
sftp-error-folder: "PATH_TO_FOLDER"
lightspeed-api-url: "BASE_URL"
lightspeed-api-key: "API_KEY"
lightspeed-api-secret-path: "PATH_TO_FILE"
lightspeed-shipment-id: "ID_FROM_LIGHTSPEED"
lightspeed-shipment-value-id: "ID_FROM_LIGHTSPEED"
master-password: "HEY_WORLD"
